apiVersion: v1
kind: Service
metadata:
  name: {{ include "claude-code-api-helm.fullname" . }}
  labels:
    {{- include "claude-code-api-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.service.ports.https.enabled }}
    - port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "claude-code-api-helm.selectorLabels" . | nindent 4 }}
